- hosts: 127.0.0.1
  tasks:
  - name: Boot up instance
    vmware_guest:
      hostname: "{{hostname}}"
      username: "{{user_name}}"
      password: "{{password}}"
      datacenter: Ojima3F-cnta
      cluster: cluster01
      folder: vlan013-sodo
      name: "{{vmname}}{{item}}"
      template: "{{template}}"
      networks:
      - name: VLAN013PortGroup
        type: dhcp
      state: poweredon
      disk:
      - datastore: vsanDatastore
        size_gb: 100
        type: thin
      - datastore: vsanDatastore
        size_gb: 100
        type: thin
      validate_certs: no
    with_sequence: count={{number}}

  - name: Wait Tools VM
    vmware_guest_tools_wait:
      hostname: "{{hostname}}"
      username: "{{user_name}}"
      password: "{{password}}"
      validate_certs: False
      name: "{{vmname}}{{item}}"
      folder: vlan013-sodo
    delegate_to: localhost
    register: facts
    with_sequence: count={{number}}

  - name: Display results (instance.ipv4)
    debug: var=item.instance.ipv4
    with_items: '{{ facts.results }}'
