- hosts: all
  tasks:

  - name: set hostname
    hostname:
      name: "{{ name }}"

  - name: Set node information
    set_fact:
      _nodes: "{{ _nodes | default([]) + [{'hostname': hostvars[item].ansible_hostname, 'address': hostvars[item].ansible_default_ipv4.address}] }}"
    run_once: yes
    with_items: "{{ ansible_play_hosts }}"

  - name: Distribute hosts file
    template:
      src: hosts.j2
      dest: /etc/hosts
      owner: root
      group: root
      mode: 0644
      backup: yes
